### ISSUE TITLE
FTL Upload plugin is displaying partially

### ISSUE THREAD

**Issue by nimishajn** [JetBrains/teamcity-deployer-plugin#112]
I am using teamcity version 2020.1.4
When I am trying to add an `FTP Upload` build step, the step is displaying partially 

![image](https://user-images.githubusercontent.com/73949899/100052860-cf916c00-2e44-11eb-93b3-17f82268b365.png)

I did not find this issue listed under known issues? Can somebody please help me fix this issue?

**Comment by nimjain-tibco** [comment]
Worked after removing contents under /work/Catalina folder in teamcity server and restarting teamcity server
