### ISSUE TITLE
SSH Deploy painfully slow

### ISSUE THREAD

**Issue by nskvortsov** [JetBrains/teamcity-deployer-plugin#26]
When deploying changes even if the change is 1 file it constantly takes around 2 minutes to deploy is something wrong with my configuration or what?![Dev Configuration -- TeamCity 2014-03-17 11-34-49 2014-03-17 11-35-10.jpg](https://bitbucket.org/repo/yxak4/images/373807862-Dev%20Configuration%20--%20TeamCity%202014-03-17%2011-34-49%202014-03-17%2011-35-10.jpg)

----------------------------------------
- Bitbucket: https://bitbucket.org/nskvortsov/deployer/issue/26
- Originally reported by: Clark Tomlinson
- Originally created at: 2014-03-17T16:35:33.552

**Comment by nskvortsov** [comment]
I guess it would help to mention im deploying a php project but i only need to push the changed files over to the remote server

----------------------------------------
Original comment by: Clark Tomlinson

**Comment by nskvortsov** [comment]
Clark,

The plugin does not have any notion of changed files. Each time, *all* files are uploaded.

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by nskvortsov** [comment]
there is no plan to do incremental ssh deploy.
If incremental deploy is absolutely necessary, please fall back to command line runner and `rsync`

----------------------------------------
Original comment by: Nikita Skvortsov

**Comment by tgourley** [comment]
This relates to a problem I am having as well.  I have a very large project, but the SSH upload took 2.5 hours because of its large size.  I need to only copy over the changed files.  It is a Windows-based install (meaning no rsync.)  Is there anything I can do to only upload changed files?

**Comment by nskvortsov** [comment]
@tgourley at this point, the incremental upload is not supported (yet).
Could you please tell, what type of SSH upload do you use (SFTP or SCP)? How do you do the deployment outside TeamCity (e.g., from your workstation)?

**Comment by nskvortsov** [comment]
Duplicates #58

**Comment by alexykot** [comment]
I'd say that there should be an option to have "rsync" as a transport protocol, with option to pass flags to it. Then those who need complex or large syncing would be able to use deployer plugin with needed settings and without a need to manually configure environment for rsync, while simple upload options will be still handled by SCP/SFTP.

**Comment by nskvortsov** [comment]
Alex, are you aware of any good rsync client libraries for jvm?
17 мая 2016 г. 0:55 пользователь "Alex Kotenko" <notifications@github.com>
написал:

**Comment by Maxim-Mazurok** [comment]
@nskvortsov, Is [perlundq/yajsync](https://github.com/perlundq/yajsync) library good for this purpose?
> are you aware of any good rsync client libraries for jvm?

**Comment by nskvortsov** [comment]
@Maxim-Mazurok thank you for the link. I did not try this library. As the deployer plugin is now bundled with the TeamCity distribution, it should follow general compatibility requirements that include all agent-side code being Java 6 compatible.  Using this rsync lib (and updating the smb lib) will require out-of-process implementation using Java 8.
