### ISSUE TITLE
ftp upload js file has change file encode

### ISSUE THREAD

**Issue by czcz1024** [JetBrains/teamcity-deployer-plugin#50]
i'v upload some js file use ftp deployer.
in the js file,contains chinses letter.
after upload,the file encoding changed from unicode (utf-8 with signature) - codepage 65001 (this is in vs) to unicode (utf-8 without signature) - codepage 65001
and all chinses letters are changed.
and also the css file
but cshtml file is right
is there any way to fix it?

i try the plugin ftp uploader,that fine to upload the js and css file

**Comment by nskvortsov** [comment]
Did you try to use `Binary` Transfer Mode in ftp deployer settings?

**Comment by czcz1024** [comment]
yes,binary is ok,thank you

**Comment by nskvortsov** [comment]
Proper use of transfer mode resolves the issue.
