### ISSUE TITLE
SMB Deployer slow copy speed

### ISSUE THREAD

**Issue by iamphi** [JetBrains/teamcity-deployer-plugin#53]
I am copying to and from Windows 2008 Servers machines.  A copy using Windows Explorer takes a few seconds to transfer a 15MB file. The machines are on separate network connected via AWS VPN; One is in an Amazon VPC.

The default SMB deployer settings takes 12mins for the 15MB file.

I've tried configuring these settings in my agent's wrapper.conf
```
wrapper.app.parameter.8=-Djcifs.smb.client.rcv_buf_size=604160
wrapper.app.parameter.9=-Djcifs.smb.client.snd_buf_size=166440
wrapper.app.parameter.10=-Djcifs.resolveOrder=DNS
wrapper.app.parameter.11=-Djcifs.smb.client.dfs.disabled=true
wrapper.app.parameter.12=-Djcifs.netbios.client.writeSize=15000

wrapper.app.parameter.13=jetbrains.buildServer.agent.AgentMain
## TeamCity agent parameters
wrapper.app.parameter.14=-file
wrapper.app.parameter.15=../conf/buildAgent.properties
```

Only these two configurations seem to have any effects:
```
wrapper.app.parameter.10=-Djcifs.resolveOrder=DNS
wrapper.app.parameter.11=-Djcifs.smb.client.dfs.disabled=true
```
With them copying takes about 5mins.

Each time I make changes to wrapper.conf, I restart the build agent service.

**Comment by nskvortsov** [comment]
Latest version of deployer plugin has an advanced option "Name resolution" 
@iamphi did you try to use it?

**Comment by nskvortsov** [comment]
Hello, @iamphi , Did you have a chance to try the option?

**Comment by iamphi** [comment]
Sorry, copying is still slow as before. I checked C:\TeamCity\buildAgent\launcher\conf\wrapper.conf to be sure that my settings are not still there.
I also had upgraded from TeamCity to 9.0.2 to 9.0.4.
Thanks for checking.

**Comment by iamphi** [comment]
I made a test program based on the smb deployer code (SMBBuildProcessAdapter.java). I found that the copy buffer is not efficient for my copy task (line 142: byte[] buf = new byte[4096]). I tested with buffer sizes 256kb, 512kb, 1mb, and 2mb and each gave me similar copy speed: copying 14MB takes just over 1 minute. Can you please make the buffer size into a customizable value or probing algorithm to find the optimal buffer size? I would like to see a customizable buffer size first. Thank you!
