### ISSUE TITLE
FTP Deploy Speed Slow

### ISSUE THREAD

**Issue by jhelmink** [JetBrains/teamcity-deployer-plugin#55]
Hey, so firstly I'd just like to say thanks for this plugin! I use it to deploy all of my projects to various servers via FTP. I've read through some of the other issues here and I'd like to share my experiences.
I deploy via regular FTP using normal credentials to an IP address.
Using FTP deployer I can deploy a build of ~1000 files totaling ~25Mb from an NZ server to a UK server in about 2 hours.
However if I use FileZilla for a manual deployment (overwriting all files) between the same servers it only takes about 20 minutes.

**Comment by jhelmink** [comment]
One thing to add to this, the main reason that this is a problem is that the build will fail 25% of the time with a "java.net.SocketTimeoutException: Read timed out" error which means a lot of lost time to re-run the build.

**Comment by alefr** [comment]
I'm seeing the same behavior when trying to deploy from an azure vps to an azure website both with North European storage.
Running the FTP upload manually from the vps is no problem but from the deployer takes a really long time and eventuell fails with a "java.net.SocketTimeoutException: Read timed out".

**Comment by jhelmink** [comment]
@alefr contact me privately contact@joshhelmink.com for an interim alternative solution.

**Comment by wedocodeuk** [comment]
I have the same problem, it appears to only open a single thread, and only uploads a single file at a time. I am considering uploading and ZIP and then setting up ssh and unzipping via that.

**Comment by vladkosarev** [comment]
About every other time we get java.net.SocketTimeoutException: Read timed out during upload to Azure ftp build step.

**Comment by nskvortsov** [comment]
Please try [this build](http://teamcity.jetbrains.com/guestAuth/repository/download/bt402/612385:id/deploy-runner.zip?guest=1) of the plugin.
Happy deploying!

**Comment by vladkosarev** [comment]
Updated the plugin now just get - java.lang.NullPointerException all the time

**Comment by nskvortsov** [comment]
@vladkosarev please attach a stacktrace

**Comment by vladkosarev** [comment]
@nskvortsov Where can I see full exception? 

I just get this in the log -
[12:54:43][Step 8/9] Exception while uploading files: null
[12:54:43][Step 8/9] java.lang.NullPointerException
[12:54:43][Step 8/9] Step Deploy to FTP (FTP Deployer) failed

Nothing in any of the logs on the server either.

**Comment by nskvortsov** [comment]
Take a look at teamcity-agent.log under logs directory. Also, enabling
agent debug logging can help.
2 нояб. 2015 г. 23:11 пользователь "Vlad Kosarev" <notifications@github.com>
написал:

**Comment by vladkosarev** [comment]
Found it -
Caused by: java.lang.NullPointerException
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.dirExists(FtpBuildProcessAdapter.java:386)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.createPath(FtpBuildProcessAdapter.java:358)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter.access$400(FtpBuildProcessAdapter.java:32)
	at jetbrains.buildServer.deployer.agent.ftp.FtpBuildProcessAdapter$1.run(FtpBuildProcessAdapter.java:221)
	... 1 more

**Comment by vladkosarev** [comment]
Could it be that newer versions don't support UNC paths?

**Comment by vladkosarev** [comment]
Installed newest TeamCity and whatever the latest build was on plugins page, reinstalled agents. Same issue. Is there a page with older versions I can try out? At this point all our deployment builds are broken due to this issue.

**Comment by nskvortsov** [comment]
@vladkosarev here is an older version of plugin:
http://teamcity.jetbrains.com/guestAuth/repository/download/bt402/619410:id/deploy-runner.zip?guest=1
Also, I have opened a new issue for the NPE https://github.com/JetBrains/teamcity-deployer-plugin/issues/68
