### ISSUE TITLE
SSH deployer authentication failure. 

### ISSUE THREAD

**Issue by indira-ak** [JetBrains/teamcity-deployer-plugin#61]
![deployplugin_issue_ssh](https://cloud.githubusercontent.com/assets/13747886/9197557/c3e0f8fc-4052-11e5-9f85-3e6a6740a49e.png)

Attachment has the full details about the settings done on teamcity build runner : SSH Deployer Authentication Issues log below,

![image](https://cloud.githubusercontent.com/assets/13747886/9197758/c91ac986-4054-11e5-841e-9aba04c5798c.png)

Questions: 
My requirement is to deploy the artifacts (created in teamcity while compiling the code) to dev server through ssh deployer.
1. how to get ride of the auth fail?
2. Please specify with some examples how each deployers are working? 
3. where should i place the private key to make it useful for teamcity to connect to any servers and deploy the artifacts to that server?

**Comment by nskvortsov** [comment]
Default private key uses ~/.ssh/id_rsa key for auth. This file is supposed to be located at Build Agent machine.

Recently, a support for SSH-Agent auth was implemented by @webner  . This feature will help you to make a key useful for connecting to any servers. It can be succefully combined with TeamCity ssh key management and ssh-agent build 

Follow these steps:
1. Upload your key to TeamCity server
2. Set up an ssh-agent build feature for your build
3. Choose ssh-agent auth. type in ssh deployer settings.
