### ISSUE TITLE
Uploaded ssh keys

### ISSUE THREAD

**Issue by mlanin** [JetBrains/teamcity-deployer-plugin#62]
While configuring ssh exec or sftp deploy, I have to choose between ssh keys authentication or password. Of course ssh keys are preferable, but I can't use uploaded ssh keys via [SSH key management](https://confluence.jetbrains.com/display/TCD8/SSH+Keys+Management) feature.

Is it possible to use them instead of manually uploading each one to build agents?

**Comment by nskvortsov** [comment]
This is covered by ssh-agent feature https://github.com/JetBrains/teamcity-deployer-plugin/pull/63
Please try latest build from [teamcity](http://teamcity.jetbrains.com/guestAuth/viewType.html?buildTypeId=bt402?guest=1)
