### ISSUE TITLE
Can't find reference for some classes

### ISSUE THREAD

**Issue by kcowgill** [JetBrains/teamcity-deployer-plugin#80]
I'm trying to modify this plugin for my own purposes by adding on to it (highly customized for my company), and am modifying the FTP Deployer.

I see references to "jetbrains.buildServer.agent.impl.artifacts.ArtifactsCollection" in a couple of places, and I've checked the official documentation at http://javadoc.jetbrains.net/teamcity/openapi/current/ but am unable to find anything.

Can I get a pointer in the right direction?

Thanks!

**Comment by nskvortsov** [comment]
Sorry, it is not really a part of the open API and no documentation is availble on the class
