### ISSUE TITLE
https container deploy fails 

### ISSUE THREAD

**Issue by ccoton** [JetBrains/teamcity-deployer-plugin#81]
Hi,

I have the plugin set to deploy to https://devdemo.mysite.com and I get a "failed to deploy" error.

The logs reveal an "unknown host" exception but it seems from the below that the url is being wrongly set: "`Setting Tomcat Manager URL to http://https://devdemo.mysite.com/manager/text`" with `http://` being appended.

Is https not supported currently?  Can this be fixed please?

Thanks
Chris

**Comment by nskvortsov** [comment]
Sounds reasonable. I have added option to switch to https.
You can download fresh build from [here](https://teamcity.jetbrains.com/viewLog.html?buildId=782616&buildTypeId=bt402&tab=artifacts)
