### ISSUE TITLE
FTP Deployer Timeout Issues

### ISSUE THREAD

**Issue by rmoat** [JetBrains/teamcity-deployer-plugin#85]
I'm not really sure were to start with this. Our Teamcity team have e-mailed me with some errors that have started for the past week or so. 
We have about 7 computers in Teamcity uploading to FTP.

On occassion they work, but the past few days we've been seeing messages like:

[Step 6/10] < 125 Data connection already open; Transfer starting.
[08:43:06][Step 6/10] Exception while uploading files: Read timed out
[08:43:06][Step 6/10] java.net.SocketTimeoutException: Read timed out
[08:43:06][Step 6/10] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_18' value='280614.0']

Not being familiar with team city, I'm not sure where to begin. I know we have around 200 Mbps bandwidth, so I am not sure if bandwidth is our issue or not. Or whether it is a Timeout value that needs to change on the Deployer plugin, etc.

**Comment by nskvortsov** [comment]
Hello,
First thing to investigate would be the FTP server log files. Please check,
I'd there are any error messages for relevant request.
10 июня 2016 г. 21:27 пользователь "rmoat" <notifications@github.com>
написал:

**Comment by rmoat** [comment]
Thanks nskvortsov,

I will update this once I do. The FTP builds have ran successfully twice now, and the team over our teamcity servers have not provided me with the log files.

**Comment by rmoat** [comment]
Alright, so looking at the logs, it looks like it's transferring quite a bit of files and then it runs into something like this and stops. Some of the logs may not look correct, there were a lot of extra characters that I tried removing from the logs...

tc:internal, 257 "/" is current directory.

tc:internal,ŸÆ;äUO<à£> PASV

tc:internal, 227 Entering Passive Mode (104,42,235,140,39,242).

tc:internal, NLST

tc:internal, 150 Opening BINARY mode data connection.

tc:internal, 226 Transfer complete.

tc:internal, CWD site

tc:internal, 250 CWD command successful.

tc:internal, PASV

tc:internal, 227 Entering Passive Mode (104,42,235,140,39,255).

tc:internal, NLST

tc:internal, 125 Data connection already open; Transfer starting.

tc:internal, {{The build WebGL::English WebGL Build #1.85.69447 {buildId=200137} has been running for more than 60 minutes. Terminating...
Error while trying to stop test with testId=null, null
Dumping threads before termination:$BUILD_PROGRESS$
$BUILD_PROGRESS$ 
java.lang.RuntimeException: java.net.SocketException: Connection reset by peer: socket write errortc:internal,]]##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_18' value='2250006.0']]
tc:internal, Step Deploy WebGL through FTP (FTP Deployer) interrupted
Step 5/9teamcity-build-step-type}
Step 6/9{Rename Nuget Package ID in pack.nuspec (Powershell)
Disabled build step Rename Nuget Package ID in pack.nuspec (Powershell) is skipped
Step 6/9}
Step 7/9"{Create NuGet Package (NuGet Pack)@@Disabled build step Create NuGet Package (NuGet Pack) is skipped
Step 7/9}
Step 8/9 {Push package to Octo (NuGet Publish)
Disabled build step Push package to Octo (NuGet Publish) is skipped
Step 8/9}
Step 9/9{OctopusDeploy: Create release Disabled build step OctopusDeploy: Create release is skipped
Step 9/9} ##teamcity[buildStatisticValue key='buildStageDuration:buildFinishing' value='78.0']tc:internal,

**Comment by rmoat** [comment]
Now they've gotten another error: 
Failed to upload artifacts via FTP.​ Reply was:​ 425 Data channel timed out due to not meeting the minimum bandwidth requirement.​

**Comment by rmoat** [comment]
I believe our firewall in that specific building was near capacity. On various days it would work, and other days it wouldn't. Since moving our team city to a different building, the issues seem to no longer exist. I'm guessing the Firewall would get near capacity and then just start resetting the FTP server connection.

**Comment by nskvortsov** [comment]
@rmoat Thank you very much for detailed follow up!
Regarding this line in build log:

> Build #1.85.69447 {buildId=200137} has been running for more than 60 minutes. Terminating...

It means that there is a Build Failure Condition configured. Any build that runs longer than 60 minutes will be terminated.

**Comment by rmoat** [comment]
@nskvortsov Interesting! Thank you for letting me know this as well, in case they get another build error like this.
