### ISSUE TITLE
Support SMB v2

### ISSUE THREAD

**Issue by BlackGad** [JetBrains/teamcity-deployer-plugin#96]
Does SMB deployer supports protocol versions higher than 1.1?

**Comment by BlackGad** [comment]
SMB v1 protocol were disabled bcs of https://www.bostonhelpdesk.com/disabling-smbv1-one-defense-against-wanna-cry-ransomware this

**Comment by nskvortsov** [comment]
At the moment, no. SMB deployer uses reliable (but old) library jCIFS, that only implements SMB v.1

**Comment by nskvortsov** [comment]
[Candidate replacement](https://github.com/hierynomus/smbj)

**Comment by BlackGad** [comment]
Already saw source code.
Will you upgrade this plugin in near future (days, months, years)?

**Comment by nskvortsov** [comment]
It may take a weeks (review classloading magic specific to jCIFS, implement new API, implement settings conversion, do testing, merge).

**Comment by BlackGad** [comment]
Thank you for response.
For now will rework smb deploy step with good old command line solution and wait for your release.

**Comment by blowsie** [comment]
Any updates on this?
SMBv1 support was removed from Windows

**Comment by blowsie** [comment]
Awesome! what release will this be available in?

**Comment by nskvortsov** [comment]
It will soon be available in TeamCity 2018.1

пт, 15 июн. 2018 г., 13:49 Sam Blowes <notifications@github.com>:
